version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser1
      POSTGRES_PASSWORD: mypassword1
      POSTGRES_DB: student_db1
    ports:
      - "5436:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data



volumes:
  postgres_data:
